### ISSUE TITLE
Transfer Repo

### ISSUE THREAD

**Issue by cdmwebs** [qcmerge/drinkup#14]
Please transfer this repo back to @cridenour or I, as the Drinkup is no longer associated with QCMerge.

**Comment by uhlenbrock** [comment]
👍

**Comment by phildebrandt** [comment]
👍

**Comment by hellogerard** [comment]
![](http://i.imgur.com/AtPPvCo.gif)

**Comment by cridenour** [comment]
👍

**Comment by mguterl** [comment]
👍

**Comment by katzenbar** [comment]
👍

**Comment by agilous** [comment]
For some reason it won't let me transfer the repo to you @cdmwebs. Will try transferring it to @cridenour.

**Comment by agilous** [comment]
Disregard my deleted message. I misread the error. Transferring the repo to you @cdmwebs.
